-- Create nutrition_tracking table for food/meal tracking
CREATE TABLE IF NOT EXISTS public.nutrition_tracking (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  user_id UUID NOT NULL,
  nutrition_date DATE NOT NULL,
  meal_type TEXT, -- breakfast, lunch, dinner, snack
  foods_consumed TEXT, -- description of what was eaten
  portion_size TEXT, -- small, medium, large
  notes TEXT,
  nutrition_quality INTEGER, -- 1-5 rating generated by AI
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(),
  updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable RLS
ALTER TABLE public.nutrition_tracking ENABLE ROW LEVEL SECURITY;

-- Create RLS policies
CREATE POLICY "Users can view their own nutrition tracking"
  ON public.nutrition_tracking
  FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can create their own nutrition tracking"
  ON public.nutrition_tracking
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own nutrition tracking"
  ON public.nutrition_tracking
  FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own nutrition tracking"
  ON public.nutrition_tracking
  FOR DELETE
  USING (auth.uid() = user_id);

-- Create trigger for updated_at
CREATE TRIGGER update_nutrition_tracking_updated_at
  BEFORE UPDATE ON public.nutrition_tracking
  FOR EACH ROW
  EXECUTE FUNCTION public.update_updated_at_column();